version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Makassar
    open-pull-requests-limit: 6
    versioning-strategy: increase-if-necessary
    groups:
      production-minor-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-minor-patch:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
